### ISSUE TITLE
New build error

### ISSUE THREAD

**Issue by EdNutting** [j-mie6/range-set#1]
Hi @j-mie6 

Sorry to be a pain but I've just tried setting up a fresh project to use Parsley and I'm running into a build error on this rangset dependency. Bashed my head against it for a while and I just can't fathom what is going wrong! Any help / ideas would be much appreciated.

Error log from cabal:

```
Preprocessing library for rangeset-0.0.1.0..
Building library for rangeset-0.0.1.0..

src\ghc\Data\RangeSet\Internal\Types.hs:1:7: error:
    lexical error in pragma at character '1'
  |
1 | {-# LANGUAGE DerivingStrategies, RoleAnnotations, CPP, Trustworthy #-}
  |       ^

src\ghc\Data\RangeSet\Internal\Heuristics.hs:1:7: error:
    lexical error in pragma at character '1'
  |
1 | {-# LANGUAGE BangPatterns, MagicHash, CPP #-}
  |       ^

src\ghc\Data\RangeSet\Internal.hs:1:7: error:
    lexical error in pragma at character '1'
  |
1 | {-# LANGUAGE MagicHash, UnboxedTuples, MultiWayIf, BangPatterns, CPP #-}
  |       ^
```

I'm guessing those error locations are garbage because they aren't accounting for whatever the preprocessor might be doing?

Platform: Windows, 64-bit, AMD

I installed GHC/etc. using GHCUp:
ghc: 9.2.7
base: 4.16.4.0
cabal: 3.6.2.0

Packages from Hackage:
parsley: 2.0.0.0
rangeset: 0.0.1.0

Please let me know what additional info would be useful.
Ed

**Comment by j-mie6** [comment]
My only guess would be that you need the `cpphs` build tool installed (which is in the cabal file): it replaces the normal GCC preprocessor, which might be causing this. But cabal should be doing that for you, given that it's in the cabal file. I've built rangeset itself with that configuration and it seems fine on my end (but with WSL2). I'll try and build `parsley` as well with the same config

**Comment by j-mie6** [comment]
Parsley also built under that configuration...

**Comment by j-mie6** [comment]
What I could do is remove the CPP from rangeset, if I split off the one source file that needs it (just for GHC specific code!) into two source directories (like I do with `parsley-core`)... I'll do that now and cut a new release.

**Comment by EdNutting** [comment]
~Huh, that gives me an idea, maybe this is a PATH issue..!~

Edit: No, that sadly didn't fix the issue.

**Comment by EdNutting** [comment]
Thanks, I'll have a run at it on Monday with the split version and see if it works. I was able to reproduce the issue just trying to build the package (from the Hackage source tarball) so should be able to see if potential fixes work without having to go via my project/parsley.

**Comment by j-mie6** [comment]
Well, I should have the release done in less than 10 minutes 🙂 

Though if this does fix it you might find that you get similar problem when trying to build parsley-core given that it also uses `cpphs`. I wouldn't be surprised if this is a Windows problem with 9.2?

**Comment by j-mie6** [comment]
`rangeset-0.1.0.0` released.

**Comment by EdNutting** [comment]
Yes that release fixed it for rangeset, but as you predicted, parsely-core results in the same issue!

Hmm, I wonder what in GHC 9.2 is broken on Windows (MinGW) but not on WSL2 / Linux native.

Is upgrading to a more recent GHC an option (if that would fix it)?

**Comment by EdNutting** [comment]
(Btw, I have just now switched to GHCUp on WSL2 and it compiled with no issue. So yes, this is definitely something odd with GHC 9.2.7 on Windows)

**Comment by j-mie6** [comment]
A downgrade may also be an option: 8.10.7 perhaps, or 9.0. I've fallen a bit behind with ensuring compat so I'm not sure if parsley-core is working on 9.4/9.6 yet. The garnish is still blocked hard on 9.0 iirc, because it needs to be entirely rewritten 🙄

**Comment by j-mie6** [comment]
Windows + GHC has always been rather shaky. I think people still say the value in 8.6.5 remaining supported is it's an actually good release on Windows
